import { 
	GOLD_KULLAQ_1,
	GOLD_KULLAQ_2,
	GOLD_KULLAQ_3,
	GOLD_KULLAQ_4,
	GOLD_KULLAQ_5,
	GOLD_KULLAQ_6,
} from "../assets/images"

import { TentIT } from "./interfaces"

export const tentsData:TentIT[] = [
  {
    id: 1,
    header: "Tent 1",
    title: "Gold Kullaq",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    images:[
      GOLD_KULLAQ_1,
      GOLD_KULLAQ_2,
      GOLD_KULLAQ_3,
      GOLD_KULLAQ_4,
      GOLD_KULLAQ_5,
      GOLD_KULLAQ_6,
    ],
    services: {
      wifi: true,
      parking: true,
      pool: true,
      breakfast: true,
      lunch: true,
      dinner: true,
      spa: true,
      bar: true,
      hotwater: true,
      airconditioning: true,
      grill:true,
    }
  },
  {
    id: 2,
    header: "Tent 1",
    title: "Gold Sumaq",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    images:[
      GOLD_KULLAQ_1,
      GOLD_KULLAQ_2,
      GOLD_KULLAQ_3,
      GOLD_KULLAQ_4,
      GOLD_KULLAQ_5,
      GOLD_KULLAQ_6,
    ],
    services: {
      wifi: true,
      parking: true,
      pool: true,
      breakfast: true,
      lunch: true,
      dinner: true,
      spa: true,
      bar: false,
      hotwater: false,
      airconditioning: true,
      grill:false,
    }
  },
  {
    id: 3,
    header: "Tent 1",
    title: "Suite Llurak",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    images:[
      GOLD_KULLAQ_1,
      GOLD_KULLAQ_2,
      GOLD_KULLAQ_3,
      GOLD_KULLAQ_4,
      GOLD_KULLAQ_5,
      GOLD_KULLAQ_6,
    ],
    services: {
      wifi: true,
      parking: true,
      pool: true,
      breakfast: true,
      lunch: true,
      dinner: true,
      spa: true,
      bar: true,
      hotwater: true,
      airconditioning: true,
      grill:false,
    }
  },
  {
    id: 4,
    header: "Tent 1",
    title: "Suite Sallary",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    images:[
      GOLD_KULLAQ_1,
      GOLD_KULLAQ_2,
      GOLD_KULLAQ_3,
      GOLD_KULLAQ_4,
      GOLD_KULLAQ_5,
      GOLD_KULLAQ_6,
    ],
    services: {
      wifi: true,
      parking: true,
      pool: true,
      breakfast: true,
      lunch: true,
      dinner: true,
      spa: true,
      bar: true,
      hotwater: true,
      airconditioning: true,
      grill:false,
    }
  },
  {
    id: 5,
    header: "Tent 1",
    title: "Suite Wayra",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    images:[
      GOLD_KULLAQ_1,
      GOLD_KULLAQ_2,
      GOLD_KULLAQ_3,
      GOLD_KULLAQ_4,
      GOLD_KULLAQ_5,
      GOLD_KULLAQ_6,
    ],
    services: {
      wifi: true,
      parking: true,
      pool: true,
      breakfast: true,
      lunch: true,
      dinner: true,
      spa: true,
      bar: true,
      hotwater: true,
      airconditioning: true,
      grill:false,
    }
  },
  {
    id: 6,
    header: "Tent 1",
    title: "Suite Yana",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    images:[
      GOLD_KULLAQ_1,
      GOLD_KULLAQ_2,
      GOLD_KULLAQ_3,
      GOLD_KULLAQ_4,
      GOLD_KULLAQ_5,
      GOLD_KULLAQ_6,
    ],
    services: {
      wifi: true,
      parking: true,
      pool: true,
      breakfast: true,
      lunch: true,
      dinner: true,
      spa: true,
      bar: false,
      hotwater: false,
      airconditioning: false,
      grill:false,
    }
  },
]
