export type {
  ContactForm,
  ComplaintForm,
  SignIn,
  SignUp,
  VerifyAcccount,
  ForgotPassword,
  User,
  CustomPrice,
  ProductCategory,
  ExperienceCategory,
  Review,
  Faq,
  NotificationDto,
  notifcationFilters,
  DiscountCode,
  webContent,
} from '@bambucamp/shared-types';

export type {
  PublicTent as Tent,
  PublicProduct as Product,
  PublicExperience as Experience,
  ClientReserveTentDto as ReserveTentDto,
  ClientReserveProductDto as ReserveProductDto,
  ClientReserveExperienceDto as ReserveExperienceDto,
  ClientCreateReserveProductDto as createReserveProductDto,
  ClientCreateReserveExperienceDto as createReserveExperienceDto,
  ClientReserve as Reserve,
  ClientReserveFormData as ReserveFormData,
} from '@bambucamp/shared-types';
