version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: bambucamp-postgres
    environment:
      POSTGRES_USER: bambucamp
      POSTGRES_PASSWORD: ${DB_PASSWORD:-bambucamp_dev}
      POSTGRES_DB: bambucamp_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bambucamp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: bambucamp-backend
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: postgresql://bambucamp:${DB_PASSWORD:-bambucamp_dev}@postgres:5432/bambucamp_db
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-in-production}
      PORT: 3000
      ADMIN_HOSTNAME: http://admin:5173
      ADMIN_HOSTNAME_2: ${ADMIN_HOSTNAME_2:-http://localhost:5173}
      CLIENT_HOSTNAME: http://client:5174
      CLIENT_HOSTNAME_2: ${CLIENT_HOSTNAME_2:-http://localhost:5174}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@bambucamp.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER:-your-email@gmail.com}
      SMTP_PASS: ${SMTP_PASS:-your-app-password}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/server:/app
      - /app/node_modules
      - backend_images:/app/public/images
    networks:
      - bambucamp-network
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm run dev"

  # Client Website
  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    container_name: bambucamp-client
    environment:
      VITE_BACKEND_URL: ${VITE_BACKEND_URL:-http://localhost:3000}
      VITE_BACKEND_PUBLIC_URL: ${VITE_BACKEND_PUBLIC_URL:-http://localhost:3000/public}
    ports:
      - "5174:5173"
    depends_on:
      - backend
    volumes:
      - ./apps/client:/app
      - /app/node_modules
    networks:
      - bambucamp-network
    command: npm run dev -- --host 0.0.0.0 --port 5173

  # Admin Dashboard
  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    container_name: bambucamp-admin
    environment:
      VITE_BACKEND_URL: ${VITE_BACKEND_URL:-http://localhost:3000}
      VITE_BACKEND_PUBLIC_URL: ${VITE_BACKEND_PUBLIC_URL:-http://localhost:3000/public}
      VITE_ENVIRONMENT: ${VITE_ENVIRONMENT:-development}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./apps/admin:/app
      - /app/node_modules
    networks:
      - bambucamp-network
    command: npm run dev -- --host 0.0.0.0 --port 5173

volumes:
  postgres_data:
  backend_images:

networks:
  bambucamp-network:
    driver: bridge
