name: Deploy Client
on:
  push:
    branches:
      - main
    paths:
      - 'apps/client/**'
      - '.github/workflows/deploy-client.yml'

jobs:
  deploy:
    environment: go_daddy
    runs-on: ubuntu-latest

    steps:
    - name: Initialize Deploy
      env:
        SLACK_MESSAGE: " * Initialize deploy of Bambucamp Client :git:"
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "${SLACK_MESSAGE}"
        curl -X POST -H 'Content-type: application/json' --data '{"text":"'"${SLACK_MESSAGE}"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      env:
        SLACK_MESSAGE: " * Installing Dependencies :npm:"
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "${SLACK_MESSAGE}"
        cd apps/client
        npm install
        curl -X POST -H 'Content-type: application/json' --data '{"text":"'"${SLACK_MESSAGE}"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Create .env file
      run: |
        cd apps/client
        echo VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }} >> .env
        echo VITE_BACKEND_PUBLIC_URL=${{ secrets.VITE_BACKEND_PUBLIC_URL }} >> .env

    - name: Build
      env:
        SLACK_MESSAGE: " * Building React App Dist Folder :vite:"
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "${SLACK_MESSAGE}"
        cd apps/client
        npm run build
        curl -X POST -H 'Content-type: application/json' --data '{"text":"'"${SLACK_MESSAGE}"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add host key to known hosts
      env:
        SLACK_MESSAGE: " * Set Connection to SSH Digital Ocean server :digital_ocean:"
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "${SLACK_MESSAGE}"
        ssh-keyscan 208.109.246.247 >> ~/.ssh/known_hosts
        curl -X POST -H 'Content-type: application/json' --data '{"text":"'"${SLACK_MESSAGE}"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Create the deployment directory if not exists
      env:
        SLACK_MESSAGE: " * Ensuring Deployment Directory Exists :file_folder:"
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "${SLACK_MESSAGE}"
        ssh bambucamp@208.109.246.247 'mkdir -p /var/www/bambucamp-frontend'
        curl -X POST -H 'Content-type: application/json' --data '{"text":"'"${SLACK_MESSAGE}"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Deploy
      env:
        SLACK_MESSAGE: " * Client App Deployed Successfully :react: :typescript:"
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "${SLACK_MESSAGE}"
        scp -r apps/client/dist/* bambucamp@208.109.246.247:/var/www/bambucamp-frontend/
        curl -X POST -H 'Content-type: application/json' --data '{"text":"'"${SLACK_MESSAGE}"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Done
      env:
        SLACK_MESSAGE: " * Client Deployed Successfully :nodejs:"
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "${SLACK_MESSAGE}"
        curl -X POST -H 'Content-type: application/json' --data '{"text":"'"${SLACK_MESSAGE}"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
